services:
  web:
    build: .
    command: python /app/manage.py runserver
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - mvp_db
      
  mvp_db: 
    image: postgres:13
    volumes:
      - postgre_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"


  react:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app
    ports:
      - "3000:3000"
    

volumes:
  postgre_data:
